### PR TITLE
[ready] Vim diff tool and shortcut 

### PR DESCRIPTION
**Pull request by tannauit**
- git mt to open mergetool with 3 views
- Ctrl + C to interupt vimdiff
- Update color

## Screenshots
Screen Shot 2019-10-16 at 11 24 33 PM

Screen Shot 2019-10-16 at 11 24 46 PM

Merge4

Screen Shot 2019-10-17 at 9 39 37 AM
Screen Shot 2019-10-17 at 9 39 22 AM

### CODE REVIEW

**Comment by tamvm** [comment]
I don't see the image for merge4?

**Comment by tannauit** [comment]
Updated

**Comment by tiendo1011** [comment]
Why do we need this?

**Comment by phuongnd08** [comment]
@tiendo1011 Look like an attempt to use vimdiff.
@tannauit I tried vimdiff before, but to me, it's too counter-intuitive, given my experience with DiffMerge.
If we are to merge this, perhaps we need some training questions to explain vimdiff

**Comment by tannauit** [comment]
Yes, I will update trainning portal after getting merged. 
I used to use DiffMerge before, it's cool. 
But when we pair we need to control together so I prefer vimdiff. We got some problem with colors so I try to custom the color.

**Pull request merged**
